config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :ratings
  resources :reviews
  resources :recipes
  get 'welcome/index'
  resources :users
  resources :recipes do
    resources :reviews
    resources :ratings
  end
  get '/' => 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

end

app/models/rating.rb
# Class for ratings of recipes
class Rating < ActiveRecord::Base
  belongs_to :crecipe
  validates :indrating, presence: true
  # validate :range
  validates :indrating, :inclusion => {:in => [1, 10]}
  validate :existing

  def range
    if indrating < 1 || indrating > 10
      # errors.add(:indrating, 'Must rate from 1 to 10!')
      redirect_to "/recipes/#{recipe_id}/ratings/new", notice: 'Recipe was successfully created.'
    end
  end

  def existing
    user1_id = user_id
    bool = false
    Recipe.find(recipe_id).ratings.each do |rating|
      bool = true if rating.user_id == user1_id
    end
    errors.add(:user_id, 'You cannot rate a recipe twice') if bool
  end
end

app/controllers/ratings_controller.rb
# Controller for Ratings
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      redirect_to "/recipes/#{@rating.recipe_id}",
      notice: 'Rating was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /ratings/1
  def update
    if @rating.update(rating_params)
      redirect_to @rating, notice: 'Rating was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /ratings/1
  def destroy
    @rating.destroy
    redirect_to ratings_url, notice: 'Rating was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rating
    @rating = Rating.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def rating_params
    params.require(:rating).permit(:indrating, :user_id, :recipe_id)
  end
end

app/helpers/ratings_helper.rb
# Module is a helper for ratings
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <strong>Your rating must be from 1 to 10 and you may only rate a recipe once. </strong>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :indrating %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :recipe_id, :value => params[:recipe_id] %>

  <div class="actions">
    <%= f.submit "Rate this recipe!" %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Indrating</th>
      <th>User</th>
      <th>Recipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.indrating %></td>
        <td><%= rating.user_id %></td>
        <td><%= rating.recipe_id %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Indrating:</strong>
  <%= @rating.indrating %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user_id %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @rating.recipe_id %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>